[build]
  command = "yarn build"
  publish = "build"
  functions = "api"

[[redirects]]
  from = "/api/*"
  to = "http://api.geonames.org"
  status = 200
  force = true

[[redirects]]
  from ="/*"
  to="/index.html"
  status=200